services:
  postgres:
    image: postgres
    container_name: decoder-course
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: decoder-course

    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
